export type User={id:number;name:string;email:string;role:'customer'|'manager';phone?:string|null};
export type EventItem={id:number;title:string;slug:string;description?:string|null;base_price:string|number;duration_hours?:number|null;image_url?:string|null;cloudinary_public_id?:string|null;featured:boolean;is_active:boolean};
export type RentalVariant={id:number;name:string;sku?:string|null;stock_quantity:number;price_adjustment:string|number;available_quantity?:number};
export type RentalItemImage={id:number;rental_item_id:number;image_path:string;cloudinary_public_id?:string|null;image_url:string;sort_order:number};
export type RentalItem={id:number;rental_category_id:number;name:string;slug:string;description?:string|null;base_price:string|number;total_stock:number;minimum_quantity:number;maximum_quantity?:number|null;track_variants:boolean;status:string;is_active?:boolean;image_url?:string|null;cloudinary_public_id?:string|null;available_quantity?:number;category?:{id:number;name:string};variants:RentalVariant[];images?:RentalItemImage[]};
export type PromoLine={id:number;quantity:number;item:RentalItem;variant?:RentalVariant|null};
export type Promotion={id:number;title:string;slug:string;description?:string|null;image_url?:string|null;cloudinary_public_id?:string|null;discount_type:'fixed'|'percent';discount_value:string|number;booking_starts_at?:string|null;booking_ends_at?:string|null;rental_start_date?:string|null;rental_end_date?:string|null;max_redemptions?:number|null;featured:boolean;items:PromoLine[];regular_total?:number;discount_total?:number;promo_total?:number};
export type Booking={id:number;booking_type:string;customer_name:string;customer_email:string;customer_phone?:string;booking_date:string;start_time:string;end_time:string;address?:string|null;latitude?:string|number|null;longitude?:string|number|null;status:string;rental_status:string;regular_subtotal:string|number;discount_total:string|number;final_total:string|number;promotion_title_snapshot?:string|null;event?:EventItem|null;rental_items?:any[];directions_url?:string|null;reschedule_status?:string|null};

export type ShowcasePhoto={id:number;title?:string|null;caption?:string|null;image_path:string;cloudinary_public_id?:string|null;image_url:string;event_date?:string|null;sort_order:number;is_active:boolean};
