<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;use App\Jobs\SendBookingTelegramNotification;use App\Models\AvailabilityBlock;use App\Models\Booking;use App\Models\Event;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class BookingController extends Controller
{
 public function mine(Request $r){return Booking::with(['event','promotion','rentalItems'])->where('user_id',$r->user()->id)->latest()->get();}
 public function event(Request $r,Event $event){$d=$r->validate(['booking_date'=>'required|date','start_time'=>'required|date_format:H:i','end_time'=>'required|date_format:H:i|after:start_time','customer_name'=>'required|string|max:120','customer_email'=>'required|email','customer_phone'=>'required|string|max:40','address'=>'nullable|string|max:500','latitude'=>'nullable|numeric','longitude'=>'nullable|numeric','notes'=>'nullable|string|max:2000']);$this->ensureScheduleOpen($d['booking_date'],$d['start_time'],$d['end_time']);$b=Booking::create([...$d,'user_id'=>$r->user()->id,'event_id'=>$event->id,'booking_type'=>'event','rental_start_date'=>$d['booking_date'],'rental_end_date'=>$d['booking_date'],'status'=>'pending','rental_status'=>'reserved','regular_subtotal'=>$event->base_price,'discount_total'=>0,'final_total'=>$event->base_price]);SendBookingTelegramNotification::dispatch($b->id,'NEW EVENT BOOKING');return response()->json($b->load('event'),201);}
 public function cancel(Request $r,Booking $booking){abort_unless($booking->user_id===$r->user()->id,403);abort_if(in_array($booking->status,['cancelled','rejected','completed']),422,'Booking can no longer be cancelled.');$booking->update(['status'=>'cancelled']);SendBookingTelegramNotification::dispatch($booking->id,'BOOKING CANCELLED');return $booking;}
 public function requestReschedule(Request $r,Booking $booking){abort_unless($booking->user_id===$r->user()->id,403);$d=$r->validate(['booking_date'=>'required|date','start_time'=>'required|date_format:H:i','end_time'=>'required|date_format:H:i|after:start_time']);$this->ensureScheduleOpen($d['booking_date'],$d['start_time'],$d['end_time'],$booking->id);$booking->update(['reschedule_requested_date'=>$d['booking_date'],'reschedule_requested_start_time'=>$d['start_time'],'reschedule_requested_end_time'=>$d['end_time'],'reschedule_status'=>'pending']);SendBookingTelegramNotification::dispatch($booking->id,'RESCHEDULE REQUEST');return $booking;}
 private function ensureScheduleOpen(string $date,string $start,string $end,?int $ignoreBooking=null):void{$from="$date $start:00";$to="$date $end:00";$blocked=AvailabilityBlock::where('start_at','<',$to)->where('end_at','>',$from)->exists();abort_if($blocked,422,'That schedule is blocked by the owner.');$q=Booking::whereDate('booking_date',$date)->where('booking_type','event')->whereNotIn('status',['cancelled','rejected'])->where('start_time','<',$end)->where('end_time','>',$start);if($ignoreBooking)$q->whereKeyNot($ignoreBooking);abort_if($q->exists(),422,'Another event booking overlaps that schedule.');}
}
